import React from 'react';
import {
  Building2,
  Building,
  Briefcase,
  Star,
  GraduationCap,
  School,
  Layout,
  MousePointer2,
  Smartphone,
  PenTool,
  Pen,
  Pencil,
  Globe,
  Award,
  Trophy,
  ShieldCheck,
  Shield,
  Video,
  CheckCircle2,
  CheckCircle,
  Check,
  Folder,
  Code,
  Palette,
  Cpu,
  Sparkles,
  TrendingUp,
  Users,
  User,
  Wallet,
  Clock,
  BookOpen,
  Search,
  MessageSquare,
  Play,
  Heart,
  ShoppingCart,
  LayoutGrid,
  FileText,
  Calendar,
  Settings,
  LogOut,
  Lock,
  Unlock,
  Bell,
  AlertCircle,
  Plus,
  Trash2,
  Edit2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Monitor,
  Tablet,
  HelpCircle,
  Mail,
  MapPin,
  LucideIcon
} from 'lucide-react';

/**
 * Static explicit dictionary mapping normalized keys (lowercase, no non-alphanumeric chars)
 * to statically imported Lucide icon components.
 * This guarantees icons render correctly in Production (SSR / Linux VPS) without tree-shaking issues.
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  // Common business / domain aliases
  business: Building2,
  building: Building2,
  building2: Building2,
  briefcase: Briefcase,
  star: Star,
  school: GraduationCap,
  graduationcap: GraduationCap,

  // Standard icon keys (lowercase)
  layout: Layout,
  mousepointer2: MousePointer2,
  mousepointer: MousePointer2,
  smartphone: Smartphone,
  mobile: Smartphone,
  phone: Smartphone,
  pentool: PenTool,
  pen: Pen,
  pencil: Pencil,
  edit: Edit2,
  edit2: Edit2,
  globe: Globe,
  award: Award,
  trophy: Trophy,
  shieldcheck: ShieldCheck,
  shield: Shield,
  video: Video,
  checkcircle2: CheckCircle2,
  checkcircle: CheckCircle,
  check: Check,
  folder: Folder,
  code: Code,
  palette: Palette,
  cpu: Cpu,
  sparkles: Sparkles,
  trendingup: TrendingUp,
  users: Users,
  user: User,
  wallet: Wallet,
  clock: Clock,
  bookopen: BookOpen,
  search: Search,
  messagesquare: MessageSquare,
  play: Play,
  heart: Heart,
  shoppingcart: ShoppingCart,
  layoutgrid: LayoutGrid,
  filetext: FileText,
  calendar: Calendar,
  settings: Settings,
  logout: LogOut,
  lock: Lock,
  unlock: Unlock,
  bell: Bell,
  alertcircle: AlertCircle,
  plus: Plus,
  trash2: Trash2,
  trash: Trash2,
  chevronleft: ChevronLeft,
  chevronright: ChevronRight,
  chevrondown: ChevronDown,
  chevronup: ChevronUp,
  monitor: Monitor,
  tablet: Tablet,
  helpcircle: HelpCircle,
  help: HelpCircle,
  mail: Mail,
  mappin: MapPin,
};

/**
 * Safely resolves an icon string name to a statically imported Lucide icon component.
 * Performs case-insensitive, symbol-stripping normalization and alias matching.
 * Returns HelpCircle as fallback component if not found (never raw string).
 */
export function getIconComponent(iconName: string): LucideIcon {
  if (!iconName || typeof iconName !== 'string') return HelpCircle;

  // Normalize: trim, lowercase, remove non-alphanumeric chars
  const normalized = iconName.trim().toLowerCase().replace(/[^a-z0-9]/g, '');

  if (ICON_MAP[normalized]) {
    return ICON_MAP[normalized];
  }

  return HelpCircle;
}

export const AVAILABLE_ICONS = [
  'Building2',
  'Star',
  'GraduationCap',
  'Folder',
  'Code',
  'Palette',
  'Briefcase',
  'Cpu',
  'Sparkles',
  'TrendingUp',
  'Users',
  'Wallet',
  'Award',
  'Clock',
  'BookOpen',
  'Globe',
  'Search',
  'MessageSquare',
  'Video',
  'Play',
  'Heart',
  'ShoppingCart',
  'LayoutGrid',
  'FileText',
  'Calendar',
  'Settings',
  'LogOut',
  'User',
  'Lock',
  'Unlock',
  'Bell',
  'CheckCircle2',
  'AlertCircle',
  'Plus',
  'Trash2',
  'Edit2',
  'ChevronLeft',
  'ChevronRight',
  'Monitor',
  'Tablet',
  'Smartphone'
];
