/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "on-primary-fixed-variant": "#003fa5",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary": "#0050cd",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "surface-dim": "#d9dadb",
        "on-tertiary-container": "#fff7f1",
        "tertiary-fixed": "#ffddb8",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed": "#002113",
        "surface-bright": "#f8f9fa",
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "surface-tint": "#0054d7",
        "background": "#f8f9fa",
        "on-secondary-container": "#00714d",
        "on-tertiary-fixed-variant": "#653e00",
        "on-error-container": "#93000a",
        "outline": "#727687",
        "on-surface-variant": "#424656",
        "on-secondary": "#ffffff",
        "surface-container": "#edeeef",
        "tertiary-container": "#a06500",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00184a",
        "inverse-primary": "#b3c5ff",
        "on-tertiary-fixed": "#2a1700",
        "on-background": "#191c1d",
        "error": "#ba1a1a",
        "primary-container": "#0866ff",
        "primary-fixed-dim": "#b3c5ff",
        "outline-variant": "#c2c6d8",
        "secondary": "#006c49",
        "secondary-fixed-dim": "#4edea3",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed-variant": "#005236",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed": "#6ffbbe",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "tertiary": "#7f4f00",
        "surface": "#f8f9fa",
        "text-heading": "#111827",
        "text-body": "#374151",
        "border-subtle": "#E5E7EB",
        "surface-card": "#FFFFFF",
        "surface-bg": "#F9FAFB"
      },
      spacing: {
        "margin-desktop": "40px",
        "unit": "8px",
        "margin-mobile": "1rem",
        "stack-xs": "0.5rem",
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "gutter": "1.5rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "sans": ["IBM Plex Sans Arabic", "sans-serif"],
        "label-md": ["IBM Plex Sans Arabic"],
        "title-md": ["IBM Plex Sans Arabic"],
        "headline-lg-mobile": ["IBM Plex Sans Arabic"],
        "display-lg": ["IBM Plex Sans Arabic"],
        "body-md": ["IBM Plex Sans Arabic"],
        "label-sm": ["IBM Plex Sans Arabic"],
        "body-lg": ["IBM Plex Sans Arabic"],
        "headline-lg": ["IBM Plex Sans Arabic"]
      },
      fontSize: {
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "display-lg": ["36px", { "lineHeight": "48px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "38px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}


