/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "surface-variant": "#d9e3f4",
        "tertiary": "#784b00",
        "secondary-fixed": "#89f5e7",
        "inverse-primary": "#b4c5ff",
        "on-surface-variant": "#434655",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#eeefff",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "on-surface": "#121c28",
        "outline-variant": "#c3c6d7",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#6bd8cb",
        "on-secondary-fixed": "#00201d",
        "on-background": "#121c28",
        "text-heading": "#111827",
        "tertiary-container": "#996100",
        "surface-tint": "#0053db",
        "error": "#ba1a1a",
        "primary": "#004ac6",
        "on-secondary-fixed-variant": "#005049",
        "surface-dim": "#d1dbec",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006a61",
        "inverse-surface": "#27313e",
        "surface-container-high": "#dfe9fa",
        "on-secondary": "#ffffff",
        "surface-bg": "#F9FAFB",
        "primary-fixed-dim": "#b4c5ff",
        "surface": "#f8f9ff",
        "on-tertiary-container": "#ffeedd",
        "outline": "#737686",
        "surface-card": "#FFFFFF",
        "background": "#f8f9ff",
        "surface-container-highest": "#d9e3f4",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-container-low": "#eef4ff",
        "inverse-on-surface": "#eaf1ff",
        "border-subtle": "#E5E7EB",
        "on-secondary-container": "#006f66",
        "secondary-container": "#86f2e4",
        "error-container": "#ffdad6",
        "surface-container": "#e5eeff",
        "on-primary-fixed-variant": "#003ea8",
        "text-body": "#374151"
      },
      spacing: {
        "margin-desktop": "40px",
        "unit": "8px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      fontFamily: {
        "sans": ["IBM Plex Sans Arabic", "sans-serif"],
        "title-lg": ["IBM Plex Sans Arabic"],
        "label-md": ["IBM Plex Sans Arabic"],
        "headline-md": ["IBM Plex Sans Arabic"],
        "headline-lg": ["IBM Plex Sans Arabic"],
        "body-lg": ["IBM Plex Sans Arabic"],
        "label-sm": ["IBM Plex Sans Arabic"],
        "display-lg": ["IBM Plex Sans Arabic"],
        "body-md": ["IBM Plex Sans Arabic"]
      }
    },
  },
  plugins: [],
}


